### ISSUE TITLE
What is the index?

### ISSUE THREAD

**Issue by bbrewington** [hbarcello/TC19_TableauSalesOps#1]
I see it referenced in the PowerPoint slide 31, with the definition "Index = practice to create one source of measurement" - could you elaborate on this?  Is it business context specific?

Here's where it's first used in the R code - looks like you have to feed it in to the function in the main.df dataframe:
https://github.com/hbarcello/TC19_TableauSalesOps/blob/acc6f84f8b4917aa1fbe6bd93598398adc48920e/territory_cluster_script.R#L9

**Comment by hbarcello** [comment]
Good question - the Index is our measure of what we think the value of that postal code is for the next 12 months.  It's basically a currency neutral measure of quota value.  In our example in the slides it's based on the calculations we do on the historical sales, transactions and number of customers.  A very simple model could have last years sales as the index number, if you expected uniform growth across the geography.  Feel free to reach out or reply if you have further questions. My email is in the slide deck :)
